// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines all actions that the frontend can trigger
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// Home Page Actions
	Action_ACTION_GET_NEARBY_SCHOOLS Action = 1 // Get nearby schools (Range Search)
	// Favorites Page Actions
	Action_ACTION_GET_FAVORITE_SCHOOLS Action = 2 // Get favorites list
	Action_ACTION_ADD_FAVORITE         Action = 3 // Add to favorites
	Action_ACTION_REMOVE_FAVORITE      Action = 4 // Remove from favorites
	Action_ACTION_SAVE_MAP_STATE       Action = 5 // Save map state (zoom/position)
	Action_ACTION_GET_MAP_STATE        Action = 6 // Get map state
	// Search Page Actions
	Action_ACTION_SEARCH_BASIC       Action = 7  // Keyword search
	Action_ACTION_SEARCH_ADVANCED    Action = 8  // Advanced filter search
	Action_ACTION_GET_FILTER_OPTIONS Action = 12 // Get available filter options (finance types, sessions)
	// Details Page
	Action_ACTION_GET_SCHOOL_DETAILS Action = 9 // Get school details
	// Settings
	Action_ACTION_UPDATE_SETTINGS Action = 10 // Update settings (language/theme)
	Action_ACTION_GET_SETTINGS    Action = 11 // Get settings
	Action_ACTION_RELOAD_DATA     Action = 13 // Reload school data from API
	Action_ACTION_SET_DEBUG_MODE  Action = 14 // Set debug mode (enable/disable logs)
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		1:  "ACTION_GET_NEARBY_SCHOOLS",
		2:  "ACTION_GET_FAVORITE_SCHOOLS",
		3:  "ACTION_ADD_FAVORITE",
		4:  "ACTION_REMOVE_FAVORITE",
		5:  "ACTION_SAVE_MAP_STATE",
		6:  "ACTION_GET_MAP_STATE",
		7:  "ACTION_SEARCH_BASIC",
		8:  "ACTION_SEARCH_ADVANCED",
		12: "ACTION_GET_FILTER_OPTIONS",
		9:  "ACTION_GET_SCHOOL_DETAILS",
		10: "ACTION_UPDATE_SETTINGS",
		11: "ACTION_GET_SETTINGS",
		13: "ACTION_RELOAD_DATA",
		14: "ACTION_SET_DEBUG_MODE",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":          0,
		"ACTION_GET_NEARBY_SCHOOLS":   1,
		"ACTION_GET_FAVORITE_SCHOOLS": 2,
		"ACTION_ADD_FAVORITE":         3,
		"ACTION_REMOVE_FAVORITE":      4,
		"ACTION_SAVE_MAP_STATE":       5,
		"ACTION_GET_MAP_STATE":        6,
		"ACTION_SEARCH_BASIC":         7,
		"ACTION_SEARCH_ADVANCED":      8,
		"ACTION_GET_FILTER_OPTIONS":   12,
		"ACTION_GET_SCHOOL_DETAILS":   9,
		"ACTION_UPDATE_SETTINGS":      10,
		"ACTION_GET_SETTINGS":         11,
		"ACTION_RELOAD_DATA":          13,
		"ACTION_SET_DEBUG_MODE":       14,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

type SetDebugModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDebugModeRequest) Reset() {
	*x = SetDebugModeRequest{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDebugModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDebugModeRequest) ProtoMessage() {}

func (x *SetDebugModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDebugModeRequest.ProtoReflect.Descriptor instead.
func (*SetDebugModeRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *SetDebugModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type RequestEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=bridge.Action" json:"action,omitempty"` // Action type
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                   // Serialized protobuf payload (e.g., RangeSearchRequest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnvelope) Reset() {
	*x = RequestEnvelope{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvelope) ProtoMessage() {}

func (x *RequestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvelope.ProtoReflect.Descriptor instead.
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *RequestEnvelope) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *RequestEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResponseEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"` // Error message if success is false
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`   // Serialized protobuf response (e.g., SchoolListResponse)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEnvelope) Reset() {
	*x = ResponseEnvelope{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvelope) ProtoMessage() {}

func (x *ResponseEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvelope.ProtoReflect.Descriptor instead.
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseEnvelope) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseEnvelope) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ResponseEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12\x06bridge\"/\n" +
	"\x13SetDebugModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"S\n" +
	"\x0fRequestEnvelope\x12&\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0e.bridge.ActionR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"k\n" +
	"\x10ResponseEnvelope\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB\b\n" +
	"\x06_error*\xa5\x03\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ACTION_GET_NEARBY_SCHOOLS\x10\x01\x12\x1f\n" +
	"\x1bACTION_GET_FAVORITE_SCHOOLS\x10\x02\x12\x17\n" +
	"\x13ACTION_ADD_FAVORITE\x10\x03\x12\x1a\n" +
	"\x16ACTION_REMOVE_FAVORITE\x10\x04\x12\x19\n" +
	"\x15ACTION_SAVE_MAP_STATE\x10\x05\x12\x18\n" +
	"\x14ACTION_GET_MAP_STATE\x10\x06\x12\x17\n" +
	"\x13ACTION_SEARCH_BASIC\x10\a\x12\x1a\n" +
	"\x16ACTION_SEARCH_ADVANCED\x10\b\x12\x1d\n" +
	"\x19ACTION_GET_FILTER_OPTIONS\x10\f\x12\x1d\n" +
	"\x19ACTION_GET_SCHOOL_DETAILS\x10\t\x12\x1a\n" +
	"\x16ACTION_UPDATE_SETTINGS\x10\n" +
	"\x12\x17\n" +
	"\x13ACTION_GET_SETTINGS\x10\v\x12\x16\n" +
	"\x12ACTION_RELOAD_DATA\x10\r\x12\x19\n" +
	"\x15ACTION_SET_DEBUG_MODE\x10\x0eB\x0eZ\f../go/pkg/pbb\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bridge_proto_goTypes = []any{
	(Action)(0),                 // 0: bridge.Action
	(*SetDebugModeRequest)(nil), // 1: bridge.SetDebugModeRequest
	(*RequestEnvelope)(nil),     // 2: bridge.RequestEnvelope
	(*ResponseEnvelope)(nil),    // 3: bridge.ResponseEnvelope
}
var file_bridge_proto_depIdxs = []int32{
	0, // 0: bridge.RequestEnvelope.action:type_name -> bridge.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	file_bridge_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
