// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: school.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type School struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // SCHOOL NO. (Primary ID)
	OriginalIds     []int64                `protobuf:"varint,25,rep,packed,name=original_ids,json=originalIds,proto3" json:"original_ids,omitempty"`       // Original IDs of merged schools
	NameEn          string                 `protobuf:"bytes,2,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`                               // ENGLISH NAME
	NameZh          string                 `protobuf:"bytes,3,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`                               // Chinese Name (zh_hk)
	AddressEn       string                 `protobuf:"bytes,4,opt,name=address_en,json=addressEn,proto3" json:"address_en,omitempty"`                      // ENGLISH ADDRESS
	AddressZh       string                 `protobuf:"bytes,5,opt,name=address_zh,json=addressZh,proto3" json:"address_zh,omitempty"`                      // Chinese Address (zh_hk)
	Latitude        float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`                                       // LATITUDE
	Longitude       float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`                                     // LONGITUDE
	DistrictEn      string                 `protobuf:"bytes,8,opt,name=district_en,json=districtEn,proto3" json:"district_en,omitempty"`                   // DISTRICT
	DistrictZh      string                 `protobuf:"bytes,9,opt,name=district_zh,json=districtZh,proto3" json:"district_zh,omitempty"`                   // District (zh_hk)
	FinanceTypesEn  []string               `protobuf:"bytes,10,rep,name=finance_types_en,json=financeTypesEn,proto3" json:"finance_types_en,omitempty"`    // FINANCE TYPE (Multiple)
	FinanceTypesZh  []string               `protobuf:"bytes,11,rep,name=finance_types_zh,json=financeTypesZh,proto3" json:"finance_types_zh,omitempty"`    // Finance Type (zh_hk) (Multiple)
	SchoolLevelEn   string                 `protobuf:"bytes,12,opt,name=school_level_en,json=schoolLevelEn,proto3" json:"school_level_en,omitempty"`       // SCHOOL LEVEL
	SchoolLevelZh   string                 `protobuf:"bytes,13,opt,name=school_level_zh,json=schoolLevelZh,proto3" json:"school_level_zh,omitempty"`       // School Level (zh_hk)
	CategoryEn      string                 `protobuf:"bytes,14,opt,name=category_en,json=categoryEn,proto3" json:"category_en,omitempty"`                  // ENGLISH CATEGORY
	CategoryZh      string                 `protobuf:"bytes,15,opt,name=category_zh,json=categoryZh,proto3" json:"category_zh,omitempty"`                  // Category (zh_hk)
	StudentGenderEn string                 `protobuf:"bytes,16,opt,name=student_gender_en,json=studentGenderEn,proto3" json:"student_gender_en,omitempty"` // STUDENTS GENDER
	StudentGenderZh string                 `protobuf:"bytes,17,opt,name=student_gender_zh,json=studentGenderZh,proto3" json:"student_gender_zh,omitempty"` // Student Gender (zh_hk)
	SessionsEn      []string               `protobuf:"bytes,18,rep,name=sessions_en,json=sessionsEn,proto3" json:"sessions_en,omitempty"`                  // SESSION (Multiple)
	SessionsZh      []string               `protobuf:"bytes,19,rep,name=sessions_zh,json=sessionsZh,proto3" json:"sessions_zh,omitempty"`                  // Session (zh_hk) (Multiple)
	ReligionEn      string                 `protobuf:"bytes,20,opt,name=religion_en,json=religionEn,proto3" json:"religion_en,omitempty"`                  // RELIGION
	ReligionZh      string                 `protobuf:"bytes,21,opt,name=religion_zh,json=religionZh,proto3" json:"religion_zh,omitempty"`                  // Religion (zh_hk)
	Telephone       string                 `protobuf:"bytes,22,opt,name=telephone,proto3" json:"telephone,omitempty"`                                      // TELEPHONE
	FaxNumber       string                 `protobuf:"bytes,23,opt,name=fax_number,json=faxNumber,proto3" json:"fax_number,omitempty"`                     // FAX NUMBER
	Website         string                 `protobuf:"bytes,24,opt,name=website,proto3" json:"website,omitempty"`                                          // WEBSITE
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *School) Reset() {
	*x = School{}
	mi := &file_school_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *School) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*School) ProtoMessage() {}

func (x *School) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use School.ProtoReflect.Descriptor instead.
func (*School) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{0}
}

func (x *School) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *School) GetOriginalIds() []int64 {
	if x != nil {
		return x.OriginalIds
	}
	return nil
}

func (x *School) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *School) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *School) GetAddressEn() string {
	if x != nil {
		return x.AddressEn
	}
	return ""
}

func (x *School) GetAddressZh() string {
	if x != nil {
		return x.AddressZh
	}
	return ""
}

func (x *School) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *School) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *School) GetDistrictEn() string {
	if x != nil {
		return x.DistrictEn
	}
	return ""
}

func (x *School) GetDistrictZh() string {
	if x != nil {
		return x.DistrictZh
	}
	return ""
}

func (x *School) GetFinanceTypesEn() []string {
	if x != nil {
		return x.FinanceTypesEn
	}
	return nil
}

func (x *School) GetFinanceTypesZh() []string {
	if x != nil {
		return x.FinanceTypesZh
	}
	return nil
}

func (x *School) GetSchoolLevelEn() string {
	if x != nil {
		return x.SchoolLevelEn
	}
	return ""
}

func (x *School) GetSchoolLevelZh() string {
	if x != nil {
		return x.SchoolLevelZh
	}
	return ""
}

func (x *School) GetCategoryEn() string {
	if x != nil {
		return x.CategoryEn
	}
	return ""
}

func (x *School) GetCategoryZh() string {
	if x != nil {
		return x.CategoryZh
	}
	return ""
}

func (x *School) GetStudentGenderEn() string {
	if x != nil {
		return x.StudentGenderEn
	}
	return ""
}

func (x *School) GetStudentGenderZh() string {
	if x != nil {
		return x.StudentGenderZh
	}
	return ""
}

func (x *School) GetSessionsEn() []string {
	if x != nil {
		return x.SessionsEn
	}
	return nil
}

func (x *School) GetSessionsZh() []string {
	if x != nil {
		return x.SessionsZh
	}
	return nil
}

func (x *School) GetReligionEn() string {
	if x != nil {
		return x.ReligionEn
	}
	return ""
}

func (x *School) GetReligionZh() string {
	if x != nil {
		return x.ReligionZh
	}
	return ""
}

func (x *School) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *School) GetFaxNumber() string {
	if x != nil {
		return x.FaxNumber
	}
	return ""
}

func (x *School) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type SchoolListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schools       []*School              `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolListResponse) Reset() {
	*x = SchoolListResponse{}
	mi := &file_school_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolListResponse) ProtoMessage() {}

func (x *SchoolListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolListResponse.ProtoReflect.Descriptor instead.
func (*SchoolListResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolListResponse) GetSchools() []*School {
	if x != nil {
		return x.Schools
	}
	return nil
}

type GetSchoolByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolByIdRequest) Reset() {
	*x = GetSchoolByIdRequest{}
	mi := &file_school_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolByIdRequest) ProtoMessage() {}

func (x *GetSchoolByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolByIdRequest.ProtoReflect.Descriptor instead.
func (*GetSchoolByIdRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchoolByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_school_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type AdvancedSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // case-insensitive contains match
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                            // case-insensitive contains match
	District      string                 `protobuf:"bytes,3,opt,name=district,proto3" json:"district,omitempty"`                          // case-insensitive contains match
	FinanceType   string                 `protobuf:"bytes,4,opt,name=finance_type,json=financeType,proto3" json:"finance_type,omitempty"` // exact match
	Session       string                 `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`                            // exact match
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvancedSearchRequest) Reset() {
	*x = AdvancedSearchRequest{}
	mi := &file_school_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvancedSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvancedSearchRequest) ProtoMessage() {}

func (x *AdvancedSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvancedSearchRequest.ProtoReflect.Descriptor instead.
func (*AdvancedSearchRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{4}
}

func (x *AdvancedSearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdvancedSearchRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AdvancedSearchRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AdvancedSearchRequest) GetFinanceType() string {
	if x != nil {
		return x.FinanceType
	}
	return ""
}

func (x *AdvancedSearchRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type FilterOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinanceTypes  []string               `protobuf:"bytes,1,rep,name=finance_types,json=financeTypes,proto3" json:"finance_types,omitempty"`
	Sessions      []string               `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Districts     []string               `protobuf:"bytes,3,rep,name=districts,proto3" json:"districts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOptionsResponse) Reset() {
	*x = FilterOptionsResponse{}
	mi := &file_school_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOptionsResponse) ProtoMessage() {}

func (x *FilterOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOptionsResponse.ProtoReflect.Descriptor instead.
func (*FilterOptionsResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{5}
}

func (x *FilterOptionsResponse) GetFinanceTypes() []string {
	if x != nil {
		return x.FinanceTypes
	}
	return nil
}

func (x *FilterOptionsResponse) GetSessions() []string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *FilterOptionsResponse) GetDistricts() []string {
	if x != nil {
		return x.Districts
	}
	return nil
}

type RangeSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLatitude  float64                `protobuf:"fixed64,1,opt,name=user_latitude,json=userLatitude,proto3" json:"user_latitude,omitempty"`
	UserLongitude float64                `protobuf:"fixed64,2,opt,name=user_longitude,json=userLongitude,proto3" json:"user_longitude,omitempty"`
	Range         float64                `protobuf:"fixed64,3,opt,name=range,proto3" json:"range,omitempty"` // in meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSearchRequest) Reset() {
	*x = RangeSearchRequest{}
	mi := &file_school_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSearchRequest) ProtoMessage() {}

func (x *RangeSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSearchRequest.ProtoReflect.Descriptor instead.
func (*RangeSearchRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{6}
}

func (x *RangeSearchRequest) GetUserLatitude() float64 {
	if x != nil {
		return x.UserLatitude
	}
	return 0
}

func (x *RangeSearchRequest) GetUserLongitude() float64 {
	if x != nil {
		return x.UserLongitude
	}
	return 0
}

func (x *RangeSearchRequest) GetRange() float64 {
	if x != nil {
		return x.Range
	}
	return 0
}

type RangeSearchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Schools       []*RangeSearchResponseDTO `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSearchResponse) Reset() {
	*x = RangeSearchResponse{}
	mi := &file_school_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSearchResponse) ProtoMessage() {}

func (x *RangeSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSearchResponse.ProtoReflect.Descriptor instead.
func (*RangeSearchResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{7}
}

func (x *RangeSearchResponse) GetSchools() []*RangeSearchResponseDTO {
	if x != nil {
		return x.Schools
	}
	return nil
}

type RangeSearchResponseDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        *School                `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"` // calculated distance in meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSearchResponseDTO) Reset() {
	*x = RangeSearchResponseDTO{}
	mi := &file_school_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSearchResponseDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSearchResponseDTO) ProtoMessage() {}

func (x *RangeSearchResponseDTO) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSearchResponseDTO.ProtoReflect.Descriptor instead.
func (*RangeSearchResponseDTO) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{8}
}

func (x *RangeSearchResponseDTO) GetSchool() *School {
	if x != nil {
		return x.School
	}
	return nil
}

func (x *RangeSearchResponseDTO) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// Favorite management
type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_school_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{9}
}

func (x *FavoriteRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

// Map state persistence
type MapState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CenterLatitude  float64                `protobuf:"fixed64,1,opt,name=center_latitude,json=centerLatitude,proto3" json:"center_latitude,omitempty"`
	CenterLongitude float64                `protobuf:"fixed64,2,opt,name=center_longitude,json=centerLongitude,proto3" json:"center_longitude,omitempty"`
	ZoomLevel       float64                `protobuf:"fixed64,3,opt,name=zoom_level,json=zoomLevel,proto3" json:"zoom_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapState) Reset() {
	*x = MapState{}
	mi := &file_school_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapState) ProtoMessage() {}

func (x *MapState) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapState.ProtoReflect.Descriptor instead.
func (*MapState) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{10}
}

func (x *MapState) GetCenterLatitude() float64 {
	if x != nil {
		return x.CenterLatitude
	}
	return 0
}

func (x *MapState) GetCenterLongitude() float64 {
	if x != nil {
		return x.CenterLongitude
	}
	return 0
}

func (x *MapState) GetZoomLevel() float64 {
	if x != nil {
		return x.ZoomLevel
	}
	return 0
}

// User settings
type UserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`                    // "en" or "zh"
	ThemeMode     string                 `protobuf:"bytes,2,opt,name=theme_mode,json=themeMode,proto3" json:"theme_mode,omitempty"` // "system", "light", "dark"
	ColorSeed     string                 `protobuf:"bytes,3,opt,name=color_seed,json=colorSeed,proto3" json:"color_seed,omitempty"` // "blue", "green", "purple", "orange", "teal"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_school_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{11}
}

func (x *UserSettings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSettings) GetThemeMode() string {
	if x != nil {
		return x.ThemeMode
	}
	return ""
}

func (x *UserSettings) GetColorSeed() string {
	if x != nil {
		return x.ColorSeed
	}
	return ""
}

var File_school_proto protoreflect.FileDescriptor

const file_school_proto_rawDesc = "" +
	"\n" +
	"\fschool.proto\x12\x06school\"\xc0\x06\n" +
	"\x06School\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\foriginal_ids\x18\x19 \x03(\x03R\voriginalIds\x12\x17\n" +
	"\aname_en\x18\x02 \x01(\tR\x06nameEn\x12\x17\n" +
	"\aname_zh\x18\x03 \x01(\tR\x06nameZh\x12\x1d\n" +
	"\n" +
	"address_en\x18\x04 \x01(\tR\taddressEn\x12\x1d\n" +
	"\n" +
	"address_zh\x18\x05 \x01(\tR\taddressZh\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistrict_en\x18\b \x01(\tR\n" +
	"districtEn\x12\x1f\n" +
	"\vdistrict_zh\x18\t \x01(\tR\n" +
	"districtZh\x12(\n" +
	"\x10finance_types_en\x18\n" +
	" \x03(\tR\x0efinanceTypesEn\x12(\n" +
	"\x10finance_types_zh\x18\v \x03(\tR\x0efinanceTypesZh\x12&\n" +
	"\x0fschool_level_en\x18\f \x01(\tR\rschoolLevelEn\x12&\n" +
	"\x0fschool_level_zh\x18\r \x01(\tR\rschoolLevelZh\x12\x1f\n" +
	"\vcategory_en\x18\x0e \x01(\tR\n" +
	"categoryEn\x12\x1f\n" +
	"\vcategory_zh\x18\x0f \x01(\tR\n" +
	"categoryZh\x12*\n" +
	"\x11student_gender_en\x18\x10 \x01(\tR\x0fstudentGenderEn\x12*\n" +
	"\x11student_gender_zh\x18\x11 \x01(\tR\x0fstudentGenderZh\x12\x1f\n" +
	"\vsessions_en\x18\x12 \x03(\tR\n" +
	"sessionsEn\x12\x1f\n" +
	"\vsessions_zh\x18\x13 \x03(\tR\n" +
	"sessionsZh\x12\x1f\n" +
	"\vreligion_en\x18\x14 \x01(\tR\n" +
	"religionEn\x12\x1f\n" +
	"\vreligion_zh\x18\x15 \x01(\tR\n" +
	"religionZh\x12\x1c\n" +
	"\ttelephone\x18\x16 \x01(\tR\ttelephone\x12\x1d\n" +
	"\n" +
	"fax_number\x18\x17 \x01(\tR\tfaxNumber\x12\x18\n" +
	"\awebsite\x18\x18 \x01(\tR\awebsite\">\n" +
	"\x12SchoolListResponse\x12(\n" +
	"\aschools\x18\x01 \x03(\v2\x0e.school.SchoolR\aschools\"&\n" +
	"\x14GetSchoolByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"\x9e\x01\n" +
	"\x15AdvancedSearchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdistrict\x18\x03 \x01(\tR\bdistrict\x12!\n" +
	"\ffinance_type\x18\x04 \x01(\tR\vfinanceType\x12\x18\n" +
	"\asession\x18\x05 \x01(\tR\asession\"v\n" +
	"\x15FilterOptionsResponse\x12#\n" +
	"\rfinance_types\x18\x01 \x03(\tR\ffinanceTypes\x12\x1a\n" +
	"\bsessions\x18\x02 \x03(\tR\bsessions\x12\x1c\n" +
	"\tdistricts\x18\x03 \x03(\tR\tdistricts\"v\n" +
	"\x12RangeSearchRequest\x12#\n" +
	"\ruser_latitude\x18\x01 \x01(\x01R\fuserLatitude\x12%\n" +
	"\x0euser_longitude\x18\x02 \x01(\x01R\ruserLongitude\x12\x14\n" +
	"\x05range\x18\x03 \x01(\x01R\x05range\"O\n" +
	"\x13RangeSearchResponse\x128\n" +
	"\aschools\x18\x01 \x03(\v2\x1e.school.RangeSearchResponseDTOR\aschools\"\\\n" +
	"\x16RangeSearchResponseDTO\x12&\n" +
	"\x06school\x18\x01 \x01(\v2\x0e.school.SchoolR\x06school\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\".\n" +
	"\x0fFavoriteRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\"}\n" +
	"\bMapState\x12'\n" +
	"\x0fcenter_latitude\x18\x01 \x01(\x01R\x0ecenterLatitude\x12)\n" +
	"\x10center_longitude\x18\x02 \x01(\x01R\x0fcenterLongitude\x12\x1d\n" +
	"\n" +
	"zoom_level\x18\x03 \x01(\x01R\tzoomLevel\"h\n" +
	"\fUserSettings\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"theme_mode\x18\x02 \x01(\tR\tthemeMode\x12\x1d\n" +
	"\n" +
	"color_seed\x18\x03 \x01(\tR\tcolorSeedB\x0eZ\f../go/pkg/pbb\x06proto3"

var (
	file_school_proto_rawDescOnce sync.Once
	file_school_proto_rawDescData []byte
)

func file_school_proto_rawDescGZIP() []byte {
	file_school_proto_rawDescOnce.Do(func() {
		file_school_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_school_proto_rawDesc), len(file_school_proto_rawDesc)))
	})
	return file_school_proto_rawDescData
}

var file_school_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_school_proto_goTypes = []any{
	(*School)(nil),                 // 0: school.School
	(*SchoolListResponse)(nil),     // 1: school.SchoolListResponse
	(*GetSchoolByIdRequest)(nil),   // 2: school.GetSchoolByIdRequest
	(*SearchRequest)(nil),          // 3: school.SearchRequest
	(*AdvancedSearchRequest)(nil),  // 4: school.AdvancedSearchRequest
	(*FilterOptionsResponse)(nil),  // 5: school.FilterOptionsResponse
	(*RangeSearchRequest)(nil),     // 6: school.RangeSearchRequest
	(*RangeSearchResponse)(nil),    // 7: school.RangeSearchResponse
	(*RangeSearchResponseDTO)(nil), // 8: school.RangeSearchResponseDTO
	(*FavoriteRequest)(nil),        // 9: school.FavoriteRequest
	(*MapState)(nil),               // 10: school.MapState
	(*UserSettings)(nil),           // 11: school.UserSettings
}
var file_school_proto_depIdxs = []int32{
	0, // 0: school.SchoolListResponse.schools:type_name -> school.School
	8, // 1: school.RangeSearchResponse.schools:type_name -> school.RangeSearchResponseDTO
	0, // 2: school.RangeSearchResponseDTO.school:type_name -> school.School
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_school_proto_init() }
func file_school_proto_init() {
	if File_school_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_school_proto_rawDesc), len(file_school_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_school_proto_goTypes,
		DependencyIndexes: file_school_proto_depIdxs,
		MessageInfos:      file_school_proto_msgTypes,
	}.Build()
	File_school_proto = out.File
	file_school_proto_goTypes = nil
	file_school_proto_depIdxs = nil
}
